# config/tenants/team-b.yaml
name: team-b
env: staging
namespaces:
  - ns1
quota:
  cpu: "2"
  memory: "4Gi"
  pods: "10"
  services: "5"
  configmaps: "10"
  secrets: "10"
limits:
  default:
    cpu: "500m"
    memory: "512Mi"
  defaultRequest:
    cpu: "100m"
    memory: "128Mi"
  max:
    cpu: "2"
    memory: "2Gi"