# config/tenants/team-c.yaml
name: team-c
env: development
namespaces:
  - ns1
  - ns2
  - ns3
quota:
  cpu: "8"
  memory: "16Gi"
  pods: "30"
  services: "15"
  configmaps: "30"
  secrets: "30"
limits:
  default:
    cpu: "1"
    memory: "1Gi"
  defaultRequest:
    cpu: "200m"
    memory: "256Mi"
  max:
    cpu: "4"
    memory: "4Gi"