# config/tenants/team-a.yaml
name: team-a
env: production
namespaces: 
  - ns1
  - ns2
quota:
  cpu: "4"
  memory: "8Gi"
  pods: "20"
  services: "10"
  configmaps: "20"
  secrets: "20"
limits:
  default:
    cpu: "500m"
    memory: "512Mi"
  defaultRequest:
    cpu: "100m"
    memory: "128Mi"
  max:
    cpu: "2"
    memory: "2Gi"