# applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-namespaces
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jihed/amazon-eks-multitenant-cluster
        revision: HEAD
        files:
        - path: "environments/*/tenant-config.yaml"
  template:
    metadata:
      name: '{{path.basename}}-tenants'
    spec:
      project: default
      source:
        repoURL: https://github.com/jihed/amazon-eks-multitenant-cluster
        targetRevision: HEAD
        path: '{{path.dir}}'
        plugin:
          name: kcl-v1.0
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true