apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: team-a-prod-apps
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
      environment: prod
    annotations:
      tenant-operator.kubernetes.io/version: v1
      team.kubernetes.io/name: team-a
      team.kubernetes.io/environment: prod
- apiVersion: v1
  kind: Namespace
  metadata:
    name: team-a-prod-tools
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
      environment: prod
    annotations:
      tenant-operator.kubernetes.io/version: v1
      team.kubernetes.io/name: team-a
      team.kubernetes.io/environment: prod
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: team-a-prod-apps-quota
    namespace: team-a-prod-apps
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
    annotations:
      tenant-operator.kubernetes.io/version: v1
      team.kubernetes.io/resource-quota: 'true'
  spec:
    hard:
      cpu: '4'
      memory: '8Gi'
      pods: '20'
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: team-a-prod-tools-quota
    namespace: team-a-prod-tools
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
    annotations:
      tenant-operator.kubernetes.io/version: v1
      team.kubernetes.io/resource-quota: 'true'
  spec:
    hard:
      cpu: '4'
      memory: '8Gi'
      pods: '20'
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: team-a-prod-apps-limits
    namespace: team-a-prod-apps
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
    annotations:
      tenant-operator.kubernetes.io/version: v1
      team.kubernetes.io/limit-range: 'true'
  spec:
    limits:
    - type: Container
      default:
        cpu: '500m'
        memory: '512Mi'
      defaultRequest:
        cpu: '100m'
        memory: '128Mi'
      max:
        cpu: '2'
        memory: '2Gi'
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: team-a-prod-tools-limits
    namespace: team-a-prod-tools
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
    annotations:
      tenant-operator.kubernetes.io/version: v1
      team.kubernetes.io/limit-range: 'true'
  spec:
    limits:
    - type: Container
      default:
        cpu: '500m'
        memory: '512Mi'
      defaultRequest:
        cpu: '100m'
        memory: '128Mi'
      max:
        cpu: '2'
        memory: '2Gi'
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: team-a-prod-apps-deny-all
    namespace: team-a-prod-apps
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
      policy-type: deny-all
    annotations:
      tenant-operator.kubernetes.io/version: v1
      networkpolicy.kubernetes.io/description: Deny all ingress and egress traffic by default
  spec:
    podSelector: {}
    policyTypes:
    - Ingress
    - Egress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: team-a-prod-tools-deny-all
    namespace: team-a-prod-tools
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
      policy-type: deny-all
    annotations:
      tenant-operator.kubernetes.io/version: v1
      networkpolicy.kubernetes.io/description: Deny all ingress and egress traffic by default
  spec:
    podSelector: {}
    policyTypes:
    - Ingress
    - Egress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: team-a-prod-apps-shared-services
    namespace: team-a-prod-apps
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
      policy-type: shared-services
    annotations:
      tenant-operator.kubernetes.io/version: v1
      networkpolicy.kubernetes.io/description: Allow access to shared services and intra-tenant communication
  spec:
    podSelector: {}
    policyTypes:
    - Ingress
    - Egress
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            team: team-a
            environment: prod
    egress:
    - to:
      - namespaceSelector:
          matchLabels:
            team: team-a
            environment: prod
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
      ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: monitoring
      ports:
      - port: 9090
        protocol: TCP
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: logging
      ports:
      - port: 24224
        protocol: TCP
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: team-a-prod-tools-shared-services
    namespace: team-a-prod-tools
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
      policy-type: shared-services
    annotations:
      tenant-operator.kubernetes.io/version: v1
      networkpolicy.kubernetes.io/description: Allow access to shared services and intra-tenant communication
  spec:
    podSelector: {}
    policyTypes:
    - Ingress
    - Egress
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            team: team-a
            environment: prod
    egress:
    - to:
      - namespaceSelector:
          matchLabels:
            team: team-a
            environment: prod
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
      ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: monitoring
      ports:
      - port: 9090
        protocol: TCP
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: logging
      ports:
      - port: 24224
        protocol: TCP
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
      access-group: apps-admin
    name: apps-admin-admin
    namespace: team-a-prod-apps
  rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
      access-group: apps-admin
    name: apps-admin-admin
    namespace: team-a-prod-tools
  rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
      access-group: tools-developer
    name: tools-developer-developer
    namespace: team-a-prod-apps
  rules:
  - apiGroups:
    - ''
    resources:
    - pods
    - services
    - configmaps
    - secrets
    - persistentvolumeclaims
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - apps
    resources:
    - deployments
    - statefulsets
    - daemonsets
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - batch
    resources:
    - jobs
    - cronjobs
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
      access-group: tools-developer
    name: tools-developer-developer
    namespace: team-a-prod-tools
  rules:
  - apiGroups:
    - ''
    resources:
    - pods
    - services
    - configmaps
    - secrets
    - persistentvolumeclaims
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - apps
    resources:
    - deployments
    - statefulsets
    - daemonsets
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - batch
    resources:
    - jobs
    - cronjobs
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
      access-group: apps-admin
    name: apps-admin-admin
    namespace: team-a-prod-apps
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: apps-admin-admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: admin-user
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
      access-group: apps-admin
    name: apps-admin-admin
    namespace: team-a-prod-tools
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: apps-admin-admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: admin-user
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
      access-group: tools-developer
    name: tools-developer-developer
    namespace: team-a-prod-apps
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: tools-developer-developer
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: developer-user
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      managed-by: kcl
      app.kubernetes.io/managed-by: kcl
      app.kubernetes.io/created-by: tenant-operator
      team: team-a
      access-group: tools-developer
    name: tools-developer-developer
    namespace: team-a-prod-tools
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: tools-developer-developer
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: developer-user
