# clusters/production/tenants/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-tenant-namespaces
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jihed/amazon-eks-multitenant-cluster.git
        revision: feature/use_var #HEAD
        files:
        - path: "clusters/production/tenants/config/*/input.yaml"
        requeueAfterSeconds: 30  # Add this for faster updates
  template:
    metadata:
      name: 'prod-{{path.basename}}-tenant'
      namespace: argocd
      annotations:
        debug.path: '{{path}}'  # Add debug annotation
        debug.file: '{{path.basename}}'  # Add debug annotation
      labels:
        tenant: '{{path.basename}}'
        environment: production
    spec:
      project: tenants-prod
      source:
        repoURL: https://github.com/jihed/amazon-eks-multitenant-cluster.git
        targetRevision: feature/use_var #HEAD
        path: clusters/production/tenants/config
        plugin:
          name: kcl-v1.0
          env:
            - name: TENANT_FILE
              value: "{{path.basename}}/input.yaml"
            - name: ENVIRONMENT
              value: "production"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true