# clusters/production/tenants/project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenants-prod
  namespace: argocd
spec:
  description: "Production Tenant Management"
  sourceRepos:
    - "https://github.com/your-org/infrastructure-gitops"
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'