tenants:
  - name: tenant1
    labels:
      team: alpha
      environment: prod
    resourceQuota:
      cpu: "4"
      memory: "8Gi"
      pods: "10"
    networkPolicy:
      enabled: true
      allowedNamespaces:
        - kube-system
        - monitoring
  - name: tenant2
    labels:
      team: beta
      environment: prod
    resourceQuota:
      cpu: "8"
      memory: "16Gi"
      pods: "20"
    networkPolicy:
      enabled: true
      allowedNamespaces:
        - kube-system