# clusters/staging/tenants/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging-generator
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jihed/amazon-eks-tenant-manager.git
        revision: HEAD
        files:
        - path: "clusters/staging/tenants/*/input.yaml"
  template:
    metadata:
      name: '{{path.basename}}-staging'
      namespace: argocd
      annotations:
        debug.path: '{{path}}'
        debug.basename: '{{path.basename}}'
      labels:
        tenant: '{{path.basename}}'
        environment: staging
    spec:
      project: tenants-staging
      source:
        repoURL: https://github.com/jihed/amazon-eks-tenant-manager.git
        targetRevision: HEAD
        path: 'clusters/staging/config'
        plugin:
          name: kcl-v1.0
          parameters:
            - name: TENANT_FILE
              string: "../tenants/{{path.basename}}/input.yaml"
            - name: ENVIRONMENT
              string: "staging"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true