# clusters/staging/tenants/project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenants-staging
  namespace: argocd
spec:
  description: "staging Tenant Manager Project"
  sourceRepos:
    - "https://github.com/jihed/amazon-eks-tenant-manager.git"
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'