# applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-namespaces
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jihed/amazon-eks-multitenant-cluster
        revision: HEAD
        files:
        - path: "tenants/*.yaml"
  template:
    metadata:
      name: '{{name}}-tenant'
      labels:
        tenant: '{{name}}'
    spec:
      project: tenants
      source:
        repoURL: https://github.com/jihed/amazon-eks-multitenant-cluster
        targetRevision: HEAD
        path: .
        plugin:
          name: kcl-v1.0
          # env:
          #   - name: TENANT_FILE
          #     value: "tenants/{{name}}.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true