# clusters/production/tenants/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-tenant-namespaces
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jihed/amazon-eks-multitenant-cluster
        revision: HEAD
        files:
        - path: "tenants/*.yaml"
  template:
    metadata:
      name: 'prod-{{name}}-tenant'
      labels:
        tenant: '{{name}}'
        environment: production
    spec:
      project: tenants
      source:
        repoURL: https://github.com/jihed/amazon-eks-multitenant-cluster
        targetRevision: HEAD
        path: tenants
        plugin:
          name: kcl
          env:
            - name: TENANT_FILE
              value: "tenants/{{values.path}}"
            - name: ENVIRONMENT
              value: "production"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true